import type { Metadata } from "next"
import { Toaster } from "sonner"
import { cn } from "~/lib/utils"
import { IRANYekanXVF } from "~/styles/font"
import "~/styles/globals.css"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import QueryProvider from "./QueryProvider"
export const metadata: Metadata = {
	title: {
		template: "%s | بامبو",
		default: "بامبو"
	},
	description: "Generated by create next app",
	robots: { index: false }
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='fa' dir='rtl'>
			<QueryProvider>
				<body
					className={cn(
						IRANYekanXVF.variable,
						"font-iranyekan",
						'[font-variation-settings:"dots"_3]',
						"bg-fa"
					)}>
					<Toaster position='top-center' dir='rtl' richColors />
					{children}
				</body>
			</QueryProvider>
		</html>
	)
}
